import {STATS,RES,COLORS,BIOMES,HEROES,BOARD,SPACE_TYPES,BOSSES,OBJECTIVES,QUESTS,ANOMALIES,RULEBOOK} from './data.js';
import {createGame,dispatch,active,decisionPlayer,statValue,targets,score,chooseAI,validateSave,exchangeAmounts} from './engine.js';
import {HELP} from './help.js';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='quetes_anomalies_plateau_v1',stats=Object.keys(STATS),heroes=Object.keys(HEROES),order=['chevalier','hommebete','arbaletrier','marchand','vicaire','heretique'];
const player=(i,solo=true)=>({name:i===0?'Quentin':solo?'Automate '+i:'Joueur '+(i+1),hero:order[i],ai:solo&&i>0});
let config={solo:true,pace:'standard',players:[player(0),player(1)]},s=null,saved=null,view='setup',tab='combat',mobile='board',selected=null,zoom=false,paused=false,timer=null,toastTimer=null,handoff=false,modal=null,resultClosed=false,saveOK=true,pendingStart=null;
try{const raw=localStorage.getItem(KEY);if(raw)saved=validateSave(JSON.parse(raw));}catch{saveOK=false;}
const btn=(label,a,disabled=false,primary=false)=>'<button class="button'+(primary?' primary':'')+'" data-action="'+esc(JSON.stringify(a))+'"'+(disabled?' disabled':'')+'>'+label+'</button>';
const ui=(label,id,primary=false,attrs='')=>'<button class="button'+(primary?' primary':'')+'" data-ui="'+id+'" '+attrs+'>'+label+'</button>';
const signed=n=>n>0?'+'+n:String(n);
const resources=p=>Object.keys(RES).map(k=>'<span title="'+RES[k].name+'" style="--resource:'+RES[k].color+'"><i class="resource-icon">'+RES[k].icon+'</i> '+p[k]+'<span class="sr-only"> '+RES[k].name+'</span></span>').join('');
function notify(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,6000);}
function save(){try{localStorage.setItem(KEY,JSON.stringify(s));saved=s;saveOK=true;}catch{saveOK=false;notify('Sauvegarde locale indisponible. Exportez votre partie pour la conserver.');}}
function header(game=false){return '<header class="header"><div class="brand"><span class="brand-mark" aria-hidden="true">Q</span><div><div class="brand-name">Quêtes d’Anomalies</div><div class="brand-caption">Le plateau · Édition numérique</div></div></div><nav class="header-actions" aria-label="Navigation">'+ui('Règles','rules')+(game?ui('Exporter','export')+ui('Menu','menu'):'')+'</nav></header>';}
function setup(){
 const focus=document.activeElement?.id,h=HEROES[config.players[0].hero];
 $('#app').innerHTML=header()+'<main class="setup"><div class="setup-heading"><div class="eyebrow">Votre prochaine aventure</div><h1>La table est prête.</h1><p>Choisissez vos personnages et entrez dans le royaume.</p></div>'+
 (saved?'<section class="resume-banner"><div><strong>Votre partie vous attend</strong><p>Manche '+saved.round+' · '+saved.players.map(p=>esc(p.name)).join(', ')+' · Fresque '+saved.fresque+'/'+saved.goal+'</p></div>'+ui(saved.finished?'Voir le classement':'Reprendre la partie','resume',true)+'</section>':'')+
 '<div class="setup-grid"><section class="panel setup-section"><h2>Préparer la partie</h2><div class="mode-select" role="group" aria-label="Mode de jeu"><button data-ui="solo" aria-pressed="'+config.solo+'" class="'+(config.solo?'active':'')+'">Solo · contre l’ordinateur</button><button data-ui="local" aria-pressed="'+!config.solo+'" class="'+(!config.solo?'active':'')+'">À plusieurs · même écran</button></div><div class="settings-row"><label>Nombre de personnages<select id="count">'+[2,3,4,5,6].map(n=>'<option '+(n===config.players.length?'selected ':'')+'value="'+n+'">'+n+' personnages</option>').join('')+'</select></label><label>Durée<select id="pace">'+[['short','Courte · 6 PV / joueur'],['standard','Classique · 10 PV / joueur'],['long','Longue · 15 PV / joueur']].map(([v,l])=>'<option value="'+v+'" '+(config.pace===v?'selected':'')+'>'+l+'</option>').join('')+'</select></label></div>'+
 '<form id="setup-form">'+config.players.map((p,i)=>'<div class="player-config"><div class="player-config-head"><span class="player-num" style="--player:'+COLORS[i]+'">'+(i+1)+'</span><label class="sr-only" for="name-'+i+'">Nom du joueur '+(i+1)+'</label><input id="name-'+i+'" data-name="'+i+'" value="'+esc(p.name)+'" maxlength="28" required autocomplete="off"><label class="sr-only" for="control-'+i+'">Contrôle du joueur '+(i+1)+'</label><select id="control-'+i+'" data-control="'+i+'"><option value="human" '+(!p.ai?'selected':'')+'>Humain</option><option value="ai" '+(p.ai?'selected':'')+'>Ordinateur</option></select></div><div class="player-config-bottom"><label>Personnage<select id="hero-'+i+'" data-hero="'+i+'">'+heroes.map(k=>'<option value="'+k+'" '+(p.hero===k?'selected':'')+'>'+HEROES[k].name+'</option>').join('')+'</select></label><p class="small muted">'+HEROES[p.hero].hp+' points de vie<br>'+HEROES[p.hero].role+'</p></div><details><summary>Statistiques et pouvoirs de '+HEROES[p.hero].name+'</summary><p class="small muted">'+HEROES[p.hero].description+' <span class="gold">'+HEROES[p.hero].scoring+'</span></p><p class="skill-note">Répartissez −2, −1, 0, 0, +1, +2. Le profil proposé est déjà valide.</p><div class="stats-setup">'+stats.map((k,j)=>'<label>'+STATS[k]+'<select id="stat-'+i+'-'+k+'" data-stat="'+i+':'+k+'">'+[-2,-1,0,1,2].map(v=>'<option value="'+v+'" '+(v===(p.stats?.[k]??HEROES[p.hero].stats[j])?'selected':'')+'>'+signed(v)+'</option>').join('')+'</select></label>').join('')+'</div></details></div>').join('')+
 '<div class="setup-footer"><button type="submit" class="button primary">Commencer l’aventure ⚑</button></div></form><p class="setup-note">Les dés, les combats et le décompte sont gérés par le jeu. Chaque joueur humain utilise cet écran à son tour.</p><div class="setup-links"><a href="#" data-ui="import">Importer une partie</a><a href="ancienne-version.html">Ancienne version et sauvegardes</a></div></section>'+
 '<aside class="setup-right"><div class="setup-art"><img class="map-preview" src="assets/carte.webp" alt="Carte du monde tirée du livre de règles"><div class="art-label"><div class="eyebrow">Cité · Forêt · Désert · Montagne</div><h3>Un royaume à conquérir</h3></div></div><div class="hero-detail"><div class="row"><span class="hero-emblem" aria-hidden="true">'+h.icon+'</span><div><div class="eyebrow">Votre personnage</div><h3>'+h.name+'</h3></div></div><p>'+h.description+'</p><p class="gold">'+h.scoring+'</p></div></aside></div><p class="footer-note">Règles issues de votre livret. Les paramètres complémentaires du parcours numérique sont détaillés dans l’aide.</p></main>';
 if(focus&&document.getElementById(focus))document.getElementById(focus).focus({preventScroll:true});
}
function players(){return '<section class="players-strip '+(s.players.length===2?'two':'')+'" style="--count:'+s.players.length+'" aria-label="Joueurs">'+s.players.map(p=>'<article class="player-card '+(p.id===s.current?'current':'')+'" style="--player:'+COLORS[p.id]+'"><div class="row between"><strong class="player-name">'+(p.id+1)+'. '+esc(p.name)+'</strong><span class="player-score">'+p.vp+' PV</span></div><p class="player-meta">'+HEROES[p.hero].name+(p.ai?' · Ordinateur':'')+'</p><div class="row"><div class="health-line"><i style="width:'+p.hp/p.maxHp*100+'%"></i></div><small>♥ '+p.hp+'/'+p.maxHp+'</small></div><div class="resource-mini">'+resources(p.res)+'</div></article>').join('')+'</section>';}
function board(){
 const p=active(s);
 return '<section class="board-panel" aria-label="Plateau de jeu"><div class="board-toolbar"><span class="board-title">Le royaume</span><div class="row">'+ui('Mon pion','center')+ui(zoom?'− Zoom':'+ Zoom','zoom')+'</div></div><div class="board-window" tabindex="0" aria-label="Carte défilante : faites glisser le plateau"><div class="board '+(zoom?'zoomed':'')+'">'+
 '<div class="board-center"><img class="board-map" src="assets/carte.webp" alt="Carte originale du livre de règles"><div class="board-shade"></div><div class="center-content"><div><div class="fresque-head"><span class="fresque-title">La fresque de l’Altération</span><strong class="gold">'+s.fresque+' / '+s.goal+'</strong></div><div class="fresque-track" role="progressbar" aria-label="Fresque" aria-valuemin="0" aria-valuemax="'+s.goal+'" aria-valuenow="'+Math.min(s.goal,s.fresque)+'"><div style="width:'+Math.min(100,s.fresque/s.goal*100)+'%"></div></div><div class="row between small"><span>Manche '+s.round+'</span><span>Prochaine Altération : '+(s.threshold+1)*10+' PV</span></div></div><div class="map-center-label"><div class="eyebrow">'+(s.finished?'Aventure terminée':'Vous êtes ici')+'</div><h2>'+BIOMES[BOARD[p.pos].biome].short+'</h2><p>'+esc(p.name)+' · Case '+(p.pos+1)+'</p></div><div class="vault"><div class="row between"><h3>La chambre forte</h3><span class="gold">'+s.vault.vp+' PV déposés</span></div><div class="vault-resources">'+resources(s.vault)+'</div></div></div></div>'+
 BOARD.map(t=>{const own=s.territories[t.id],tokens=s.players.filter(x=>x.pos===t.id),label=t.type==='territory'?t.difficulty+(own?.level||1)-1:t.type==='resource'?RES[BIOMES[t.biome].resource].icon:({camp:'Camp',start:'Départ',quest:'Quête',anomaly:'Anom.',tower:'Tour',obelisk:'Obél.'}[t.type]);return '<button id="space-'+t.id+'" data-ui="space" data-id="'+t.id+'" data-biome="'+t.biome+'" class="space '+t.type+(t.id===p.pos?' here':'')+(selected===t.id?' selected':'')+(own?' owned':'')+'" style="grid-row:'+(t.row+1)+';grid-column:'+(t.col+1)+';--biome:'+BIOMES[t.biome].color+';--owner:'+(own?COLORS[own.owner]:'transparent')+'" aria-label="Case '+(t.id+1)+', '+esc(t.name)+', '+BIOMES[t.biome].short+(tokens.length?', '+tokens.map(x=>esc(x.name)).join(' et '):'')+'" title="'+esc(t.name)+'"><span class="space-number">'+(t.id+1)+'</span><span class="space-icon" aria-hidden="true">'+(own?.altar?'✥':SPACE_TYPES[t.type].icon)+'</span><span class="space-label">'+label+'</span>'+(s.traps.some(x=>x.pos===t.id)?'<span class="trap-marker">×</span>':'')+'<span class="tokens">'+tokens.map(x=>'<span class="token" style="--player:'+COLORS[x.id]+'">'+(x.id+1)+'</span>').join('')+'</span></button>';}).join('')+
 '</div></div><div class="legend">'+BIOMES.map(b=>'<span><i style="background:'+b.color+'"></i>'+b.short+'</span>').join('')+'<span>♜ Territoire</span><span>✦ Anomalie</span><span>⌂ Campement</span></div><p class="board-hint">Parcours numérique de 48 cases · Sens horaire · Cliquez sur une case pour l’inspecter.</p></section>';
}
const canPlay=()=>!s.finished&&!active(s).ai&&!s.pending.length&&!handoff&&s.phase!=='done';
function turn(){
 const p=active(s),ai=decisionPlayer(s).ai;
 return '<section class="panel turn-panel" style="--player:'+COLORS[p.id]+'"><div class="row between"><div><div class="eyebrow">Manche '+s.round+' · '+(s.finished?'Fin de partie':'À votre tour')+'</div><h2>'+esc(p.name)+'</h2></div><span class="hero-emblem" aria-hidden="true">'+HEROES[p.hero].icon+'</span></div><div class="turn-controls"><div class="die" aria-label="Dé de déplacement : '+(s.moveDie??'à lancer')+'">'+(s.moveDie??'◇')+'<small>D10</small></div>'+
 (s.finished?ui('Voir le classement','results',true):s.phase==='move'?btn('Lancer le déplacement',{type:'move'},!canPlay(),true):btn(s.phase==='done'?'Passer au joueur suivant':'Terminer mon tour',{type:'end'},p.ai||!!s.pending.length||handoff,true))+
 '</div><p class="turn-instruction">'+(s.finished?'Monopoles et bonus ont été ajoutés au classement.':s.pending.length?'Un événement attend d’être résolu.':s.phase==='move'?'Lancez le D10. Votre pion avancera du nombre de cases obtenu.':s.phase==='done'?'Votre personnage est revenu au campement. Ce tour est terminé.':s.turn.retry?'Homme-Bête : vous pouvez retenter votre combat raté.':s.turn.attacks?'Attaque effectuée. Vos autres actions restent disponibles.':'Choisissez une cible, accomplissez vos quêtes ou utilisez votre pouvoir.')+'</p><div class="turn-progress"><span class="'+(s.turn.moved?'complete':'')+'">1. Déplacement</span><span class="'+(s.turn.attacks?'complete':'')+'">2. Actions</span><span>3. Fin du tour</span></div>'+(ai&&!s.finished?'<div class="row between ai-status"><span>'+(paused?'Ordinateur en pause':'L’ordinateur réfléchit…')+'</span>'+ui(paused?'Reprendre':'Pause','pause')+'</div>':'')+'</section>';
}
function location(id,inspection=false){
 const t=BOARD[id],p=active(s),own=s.territories[id],local=id===p.pos,enabled=canPlay()&&s.phase==='act'&&!s.turn.location&&local;let text='',buttons='';
 if(t.type==='territory'){text='Difficulté '+(t.difficulty+(own?.level||1)-1)+' · '+(own?'Niveau '+own.level+' · '+esc(s.players[own.owner].name)+(own.altar?' · Autel protecteur':''):'Territoire neutre');const available=canPlay()&&targets(s).some(x=>x.kind==='territory'&&x.id===id);buttons=btn(own?.owner===p.id?'Fortifier':'Attaquer',{type:'attack',kind:'territory',id},!available);if(p.hero==='marchand'&&own?.owner!==p.id)buttons+=btn('Acheter · '+(t.difficulty+(own?.level||1)-1)+' Or',{type:'buy',id},!available||p.res.or<t.difficulty+(own?.level||1)-1);}
 if(['start','camp'].includes(t.type)){text=t.type==='start'?'À chaque passage : +1 PV, revenu des territoires, recharge de compétence.':'Ce camp devient votre point de retour lorsque vous le traversez.';if(local){text+=' Sur place : un pouvoir pour 2 Or.';buttons=['heal','potion','cleanse','skill'].map(power=>btn({heal:'Soin +4',potion:'Potion',cleanse:'Purifier',skill:'Recharge'}[power],{type:'camp',power},!enabled||p.res.or<2)).join('');}}
 if(t.type==='quest')text='À l’arrivée, piochez une quête de chasse ou de charité.';
 if(t.type==='anomaly')text='À l’arrivée, une Anomalie est tirée et appliquée au joueur indiqué.';
 if(t.type==='resource')text='À l’arrivée : +'+({or:3,cuivre:2,argent:1,obsidienne:1}[BIOMES[t.biome].resource])+' '+RES[BIOMES[t.biome].resource].name+'.';
 if(t.type==='obelisk'){text='Sur place : rechargez une compétence bloquée pour 2 Or.';if(local)buttons=btn('Recharger · 2 Or',{type:'obelisk'},!enabled||p.res.or<2||!p.skillLocked);}
 if(t.type==='tower'){text='Un don par visite. Chaque palier ne peut être donné qu’une fois par personnage.';if(local)buttons=[1,2,3].map(tier=>btn(tier*2+' Or → '+(tier===1?0:1)+' PV',{type:'tower',tier},!enabled||p.res.or<tier*2||p.towerTiers.includes(tier))).join('');}
 return '<section class="panel location-card '+(inspection?'':'side-location')+'" style="--biome:'+BIOMES[t.biome].color+'"><div class="eyebrow">'+(inspection?'Case inspectée':'Votre case')+' '+(id+1)+' · '+BIOMES[t.biome].short+'</div><h3>'+SPACE_TYPES[t.type].icon+' '+t.name+'</h3><p>'+text+'</p>'+(buttons?'<div class="card-buttons">'+buttons+'</div>':'')+(t.type==='quest'&&local?'<div class="card-buttons">'+ui('Consulter mes quêtes','quests')+'</div>':'')+'</section>';
}
function combat(){
 const p=active(s),all=targets(s),enabled=canPlay();let html='';
 if(p.hero==='heretique')html+='<label>Statistique du prochain combat<select id="stat-choice"><option value="">Dé aléatoire · gratuit</option>'+stats.map(k=>'<option value="'+k+'" '+(p.hp<=1?'disabled':'')+'>'+STATS[k]+' ('+signed(statValue(p,k))+') · 1 vie</option>').join('')+'</select></label>';
 if(s.phase==='move')html+='<p class="empty">Déplacez-vous pour découvrir les cibles à portée.</p>';
 else if(s.turn.attacks&&!s.turn.retry)html+='<p class="empty">Votre attaque a été utilisée. Les quêtes de charité et les autres actions restent disponibles.</p>';
 for(const kind of ['territory','boss','player']){const list=all.filter(t=>t.kind===kind);if(!list.length)continue;html+='<div class="section-label">'+{territory:'Territoires à portée',boss:'Boss de biome',player:'Adversaires à portée'}[kind]+'</div>';for(const t of list)html+='<article class="action-card"><div class="row between"><h3>'+esc(t.name)+'</h3><span class="tag">'+BIOMES[t.biome].short+'</span></div><p>'+(kind==='player'?'Duel · '+s.players[t.id].hp+' points de vie':'Difficulté '+t.difficulty+(t.kind==='boss'?' · +'+t.reward+' PV':t.owned?' · Votre territoire':t.neutral?' · Neutre':' · Territoire adverse'))+'</p><div class="card-buttons">'+btn(s.turn.retry?'Retenter':t.owned?'Fortifier':'Attaquer',{type:'attack',kind,id:t.id},!enabled)+(p.hero==='marchand'&&kind==='territory'&&!t.owned?btn('Acheter · '+t.difficulty+' Or',{type:'buy',id:t.id},!enabled||p.res.or<t.difficulty):'')+'</div></article>';}
 if(!s.turn.attacks)html+='<p class="small muted">Posséder deux territoires d’un biome débloque son boss. Les chasses se jouent dans l’onglet Quêtes.</p>';return html;
}
function quests(){
 const p=active(s),all=targets(s);if(!p.quests.length)return '<p class="empty">Arrivez sur une case Quête pour recevoir une mission.</p>';
 return p.quests.map(id=>{const q=QUESTS.find(q=>q.id===id),eligible=q.type==='charity'?p.res[q.resource]>=q.amount:all.some(t=>t.kind==='hunt'&&t.id===id);return '<article class="action-card"><div class="row between"><h3>'+q.title+'</h3><span class="gold">+'+q.reward+' PV</span></div><p>'+q.text+'</p><p>'+(q.type==='hunt'?'Chasse · '+BIOMES[q.biome].short:'Charité · Vos réserves : '+p.res[q.resource]+' '+RES[q.resource].name)+'</p><div class="card-buttons">'+btn(q.type==='hunt'?'Tenter la chasse':'Accomplir la quête',q.type==='hunt'?{type:'attack',kind:'hunt',id}:{type:'charity',id},!canPlay()||!eligible)+'</div>'+(!eligible&&q.type==='hunt'?'<p>Il faut être à portée du biome et disposer de son attaque.</p>':'')+'</article>';}).join('');
}
function objectives(){const p=active(s);return '<p class="small muted">Le premier à payer remporte l’objectif. Chaque ressource compte aussi pour un monopole de 3 PV au décompte final.</p>'+OBJECTIVES.map(o=>'<article class="action-card"><div class="row between"><h3>Objectif '+RES[o.id].name+'</h3><span class="gold">+3 PV</span></div><p>'+o.cost+' '+RES[o.id].name+' · Vous en possédez '+p.res[o.id]+'.</p><div class="card-buttons">'+btn(s.objectives.includes(o.id)?'Déjà remporté':'Acheter · '+o.cost+' '+RES[o.id].name,{type:'objective',id:o.id},!canPlay()||s.objectives.includes(o.id)||p.res[o.id]<o.cost)+'</div></article>').join('');}
function exchanges(){const p=active(s),left=(p.hero==='marchand'?2:1)-s.turn.exchanges;return '<p class="small muted">'+left+' échange(s) forcé(s) disponible(s) ce tour.</p><label>Avec qui ?<select id="exchange-target">'+s.players.filter(x=>x.id!==p.id).map(x=>'<option value="'+x.id+'">'+esc(x.name)+'</option>').join('')+'</select></label><div class="settings-row"><label>Vous donnez<select id="exchange-give">'+Object.keys(RES).map(k=>'<option value="'+k+'">'+RES[k].name+'</option>').join('')+'</select></label><label>Vous recevez<select id="exchange-take">'+Object.keys(RES).map(k=>'<option value="'+k+'" '+(k==='cuivre'?'selected':'')+'>'+RES[k].name+'</option>').join('')+'</select></label></div><p id="exchange-preview" class="small gold"></p>'+ui('Effectuer l’échange','exchange',true,!canPlay()||!left?'disabled':'')+'<p class="small muted">1 Cuivre = 2 Or · 1 Argent = 3 Or · 1 Obsidienne = 4 Or. Les échanges conservent la valeur des ressources.</p>';}
function ability(){
 const p=active(s),h=HEROES[p.hero];let target='';
 if(['vicaire','heretique'].includes(p.hero))target='<label>Cible<select id="skill-target">'+s.players.filter(x=>p.hero==='vicaire'||x.id!==p.id).map(x=>'<option value="'+x.id+'">'+esc(x.name)+'</option>').join('')+'</select></label>';
 if(p.hero==='chevalier'){const ts=Object.entries(s.territories).filter(([,t])=>t.owner===p.id&&!t.altar);target='<label>Territoire<select id="skill-target">'+(ts.length?ts.map(([id])=>'<option value="'+id+'">'+BOARD[id].name+'</option>').join(''):'<option value="">Aucun territoire disponible</option>')+'</select></label>';}
 const usable=p.hero==='marchand'?p.purses>0:!s.turn.skill&&!p.skillLocked&&(p.hero!=='chevalier'||Object.values(s.territories).some(t=>t.owner===p.id&&!t.altar));
 return '<section class="panel ability-box"><div class="row between"><h3>'+h.icon+' '+h.name+'</h3><span class="tag">♥ '+p.hp+'/'+p.maxHp+'</span></div><p>'+h.description+'</p><div class="ability-controls">'+target+ui(p.hero==='marchand'?'Ouvrir une bourse ('+p.purses+')':h.skill,'skill',false,!canPlay()||!usable?'disabled':'')+'</div>'+(p.skillLocked?'<p class="bad small">Compétence bloquée : recharge nécessaire.</p>':'')+'<hr>'+btn(p.potion?'Boire une potion · +4 vie':'Potion vide',{type:'potion'},!canPlay()||!p.potion||p.hp===p.maxHp)+'<div class="stats-bar">'+stats.map(k=>'<div><span>'+STATS[k]+'</span><b class="'+(statValue(p,k)>0?'good':statValue(p,k)<0?'bad':'')+'">'+signed(statValue(p,k))+'</b></div>').join('')+'</div><p class="score-help">'+h.scoring+'</p></section>';
}
function roll(){const r=s.lastRoll;return !r?'':'<section class="roll-result '+(r.win?'':'failed')+'" aria-label="Résultat du combat"><div class="row between"><h3>'+(r.win?'Combat remporté':'Combat manqué')+'</h3><span class="tag">'+STATS[r.stat]+(r.critical?' · Critique':'')+'</span></div><p class="roll-equation">'+r.dice.join(' + ')+' '+signed(r.modifier)+(r.bonus?' +'+r.bonus:'')+' = '+r.total+'</p><p class="small muted">'+esc(r.target)+' · Seuil '+r.targetTotal+(r.defenderDie?' · Dé adverse '+r.defenderDie:'')+'</p></section>';}
function game(){
 const w=$('.board-window'),scroll=w?{x:w.scrollLeft,y:w.scrollTop}:null,p=active(s);
 $('#app').innerHTML=header(true)+'<main class="shell mobile-'+mobile+'">'+players()+'<div class="game-grid"><div class="board-column">'+board()+location(selected??p.pos,true)+'<section class="panel journal-panel"><div class="journal-head row between"><h3>Journal d’aventure</h3><span class="tag">Manche '+s.round+'</span></div><ol class="journal-list">'+s.log.slice(0,35).map(e=>'<li class="log-'+e.kind+'"><span class="log-round">M'+e.round+'</span>'+esc(e.text)+'</li>').join('')+'</ol></section></div><aside class="side-column">'+turn()+'<nav class="mobile-nav" aria-label="Vue du jeu"><button data-ui="mobile-board" class="'+(mobile==='board'?'active':'')+'">Plateau</button><button data-ui="mobile-actions" class="'+(mobile==='actions'?'active':'')+'">Actions de ce tour</button></nav>'+location(p.pos)+roll()+'<section class="panel action-panel"><nav class="tabs" aria-label="Actions de jeu">'+[['combat','Combats'],['quests','Quêtes'],['objectives','Objectifs'],['exchange','Échange']].map(([k,l])=>'<button data-ui="tab" data-tab="'+k+'" class="'+(tab===k?'active':'')+'" aria-pressed="'+(tab===k)+'">'+l+(k==='quests'?' ('+p.quests.length+')':'')+'</button>').join('')+'</nav><div class="tab-content">'+({combat,quests,objectives,exchange:exchanges}[tab]())+'</div></section>'+ability()+'</aside></div><footer class="footer-note"><span class="'+(saveOK?'good':'bad')+'">'+(saveOK?'Partie sauvegardée sur cet appareil':'Sauvegarde indisponible · exportez la partie')+'</span><a href="'+RULEBOOK+'" target="_blank" rel="noopener">Livre de règles original</a></footer></main>';
 if(scroll&&$('.board-window')){$('.board-window').scrollLeft=scroll.x;$('.board-window').scrollTop=scroll.y;}if(tab==='exchange')exchangePreview();
}
function center(){const w=$('.board-window'),cell=s?$('#space-'+active(s).pos):null;if(!w||!cell)return;const a=w.getBoundingClientRect(),b=cell.getBoundingClientRect();w.scrollLeft+=b.left-a.left-w.clientWidth/2+b.width/2;w.scrollTop+=b.top-a.top-w.clientHeight/2+b.height/2;}
function dh(title,sub='',close=true){return '<div class="dialog-header"><div>'+(sub?'<div class="eyebrow">'+sub+'</div>':'')+'<h2 id="dialog-title">'+title+'</h2></div>'+(close?ui('Fermer','close'):'')+'</div>';}
function open(html,closable=true){const d=$('#dialog');d.innerHTML=html;d.setAttribute('aria-labelledby','dialog-title');d.dataset.closable=String(closable);if(!d.open)d.showModal();}
function cardText(c){const effect=c.effect==='resource'?signed(c.amount)+' '+RES[c.resource].name:c.effect==='health'?signed(c.amount)+' points de vie':c.effect==='skill'?(c.sign>0?'Recharge de compétence':'Compétence bloquée jusqu’à recharge'):c.effect==='potion'?(c.sign>0?'Recharge de potion':'Potion vidée'):(c.sign>0?'Bénédiction +1':'Malédiction −1')+' sur une statistique aléatoire';return effect+' pour '+({self:'le joueur qui choisit',next:'le joueur suivant',previous:'le joueur précédent'}[c.target])+'.';}
function pending(){
 const d=s.pending[0],p=s.players[d.chooser];
 if(d.kind==='death'){open(dh('Retour au campement',esc(p.name),false)+'<p class="dialog-intro">'+esc(p.name)+' revient à la case '+(p.camp+1)+' avec '+p.hp+'/'+p.maxHp+' points de vie. Choisissez gratuitement un pouvoir.</p><div class="dialog-cards">'+[['heal','Se soigner · +4 vie'],['potion','Recharger la potion'],['cleanse','Dissiper les effets négatifs'],['skill','Recharger la compétence']].map(([power,l])=>btn(l,{type:'revive',power},p.ai)).join('')+'</div><div class="dialog-footer">'+ui('Menu','menu')+'</div>',false);return;}
 const alt=d.kind==='alteration';
 open(dh(alt?'L’Altération s’éveille':'Une Anomalie apparaît',(alt?'Palier '+d.level+' · ':'')+esc(p.name)+' choisit',false)+'<p class="dialog-intro">'+(alt?'Choisissez une carte. Les autres joueurs choisiront ensuite dans l’ordre.':'Appliquez la carte au joueur indiqué.')+'</p>'+
 (p.hero==='vicaire'?'<label>Redirection du Vicaire<select id="anomaly-target"><option value="">Conserver la cible indiquée</option>'+s.players.map(x=>'<option value="'+x.id+'">'+esc(x.name)+'</option>').join('')+'</select></label><hr>':'')+
 '<div class="dialog-cards">'+d.cards.map(id=>{const c=ANOMALIES[id];return '<article class="anomaly-card '+(c.sign<0?'negative':'')+'"><div class="row between"><h3>'+c.title+'</h3><span class="tag">'+(c.sign>0?'Faveur':'Épreuve')+'</span></div><p>'+cardText(c)+'</p><div class="card-buttons">'+btn(alt?'Choisir cette carte':'Appliquer l’anomalie',{type:'anomaly',id},p.ai,true)+(alt?btn('À tous · 2 PV',{type:'anomaly',id,global:true},p.ai||p.vp<2):'')+'</div></article>';}).join('')+'</div>'+(p.ai?'<p class="dialog-intro">L’ordinateur choisit sa carte…</p>':'')+'<div class="dialog-footer">'+ui('Menu','menu')+'</div>',false);
}
function results(){const rows=score(s),winners=rows.filter(r=>r.total===rows[0].total);open(dh('Le royaume a choisi','Fin de l’aventure')+'<h3 class="winning-title">'+(winners.length>1?'Victoire partagée':esc(winners[0].name)+' l’emporte')+'.</h3><p class="dialog-intro">'+(winners.length>1?winners.map(x=>esc(x.name)).join(' et ')+' terminent à égalité. ':'')+'Les monopoles et les bonus des personnages sont inclus.</p>'+rows.map(r=>'<div class="result-rank"><span class="rank">'+(rows.findIndex(x=>x.total===r.total)+1)+'</span><div class="result-info"><strong>'+esc(r.name)+'</strong><p>'+HEROES[r.hero].name+' · Base '+r.base+' PV<br>Monopoles +'+r.monopolies.length*3+(r.monopolies.length?' ('+r.monopolies.map(k=>RES[k].name).join(', ')+')':'')+' · Personnage +'+r.character+'</p></div><span class="result-total">'+r.total+' <small>PV</small></span></div>').join('')+'<div class="dialog-footer">'+ui('Exporter la partie','export')+ui('Retour à la table','menu',true)+'</div>');}
function render(){
 clearTimeout(timer);if(view==='setup'){setup();if(!modal&&$('#dialog').open)$('#dialog').close();return;}game();if(modal)return;
 if(s.pending.length)pending();else if(handoff)open(dh('À vous de jouer','Manche '+s.round,false)+'<p class="dialog-intro">Passez l’écran à <strong>'+esc(active(s).name)+'</strong>, qui incarne '+HEROES[active(s).hero].name+'.</p>'+ui('Je suis prêt','ready',true),false);else if(s.finished&&!resultClosed)results();else if($('#dialog').open)$('#dialog').close();schedule();
}
function schedule(){clearTimeout(timer);if(view!=='game'||!s||s.finished||modal||handoff||paused||!decisionPlayer(s).ai)return;timer=setTimeout(()=>{try{perform(chooseAI(s),true);}catch(e){paused=true;notify('Tour automatique en pause : '+e.message);render();}},700);}
function perform(a,automated=false){
 if(!s)return;if(!automated&&decisionPlayer(s).ai)return notify('C’est à l’ordinateur de jouer.');
 if(a.type==='attack'&&!automated&&$('#stat-choice')?.value)a.stat=$('#stat-choice').value;
 if(a.type==='anomaly'&&!automated&&!a.global){const target=$('#anomaly-target')?.value;if(target!==undefined&&target!=='')a.target=+target;}
 const previous=s.current;s=dispatch(s,a);save();
 if(a.type==='move'){selected=null;mobile='actions';}if(a.type==='attack'||a.type==='buy')mobile='actions';
 if(a.type==='end'&&previous!==s.current){selected=null;tab='combat';mobile='board';handoff=!active(s).ai&&s.players.filter(p=>!p.ai).length>1;}
 $('#announcement').textContent=s.log.slice(0,2).map(e=>e.text).reverse().join(' ');render();if(a.type==='move'||a.type==='end')requestAnimationFrame(center);
}
function start(){
 const apply=()=>{s=createGame(config,crypto.getRandomValues(new Uint32Array(1))[0]);view='game';modal=null;handoff=false;resultClosed=false;paused=false;tab='combat';mobile='board';selected=null;save();$('#dialog').close();render();requestAnimationFrame(center);window.scrollTo(0,0);};
 if(saved&&!saved.finished){pendingStart=apply;modal='replace';open(dh('Commencer une nouvelle partie')+'<p class="dialog-intro">La sauvegarde automatique actuelle sera remplacée. Vous pouvez l’exporter avant de continuer.</p><div class="dialog-footer">'+ui('Exporter la partie actuelle','export-saved')+ui('Commencer la nouvelle partie','confirm-start',true)+'</div>');}else apply();
}
function exportFile(value){if(!value)return notify('Aucune partie à exporter.');const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='quetes-anomalies-manche-'+value.round+'.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);notify('La sauvegarde est prête à être enregistrée.');}
function exchangePreview(){if(!$('#exchange-preview'))return;try{const give=$('#exchange-give').value,take=$('#exchange-take').value,n=exchangeAmounts(give,take),other=s.players[+$('#exchange-target').value];$('#exchange-preview').textContent=n.give+' '+RES[give].name+' → '+n.take+' '+RES[take].name+' · Vos réserves : '+active(s).res[give]+' · '+other.name+' : '+other.res[take];}catch(e){$('#exchange-preview').textContent=e.message;}}
document.addEventListener('click',e=>{
 const a=e.target.closest('[data-action]');if(a&&!a.disabled){try{perform(JSON.parse(a.dataset.action));}catch(err){notify(err.message);}return;}
 const el=e.target.closest('[data-ui]');if(!el||el.disabled)return;e.preventDefault();const k=el.dataset.ui;
 try{
  if(k==='rules'){clearTimeout(timer);modal='rules';open(dh('Comment jouer','Quêtes d’Anomalies')+'<div class="rules-content">'+HELP+'</div>');}
  else if(k==='close'){modal=null;resultClosed=true;$('#dialog').close();render();}
  else if(k==='solo'||k==='local'){config.solo=k==='solo';config.players=config.players.map((p,i)=>({...p,ai:config.solo&&i>0,name:i===0?p.name:config.solo?'Automate '+i:'Joueur '+(i+1)}));setup();}
  else if(k==='resume'){s=saved;view='game';modal=null;handoff=false;resultClosed=false;render();requestAnimationFrame(center);window.scrollTo(0,0);}
  else if(k==='menu'){view='setup';modal=null;handoff=false;clearTimeout(timer);$('#dialog').close();render();window.scrollTo(0,0);}
  else if(k==='ready'){handoff=false;render();requestAnimationFrame(center);}
  else if(k==='tab'){tab=el.dataset.tab;render();}
  else if(k==='mobile-board'||k==='mobile-actions'){mobile=k.slice(7);render();if(mobile==='board')requestAnimationFrame(center);}
  else if(k==='space'){selected=+el.dataset.id;render();}
  else if(k==='center')center();
  else if(k==='zoom'){zoom=!zoom;render();requestAnimationFrame(center);}
  else if(k==='quests'){tab='quests';mobile='actions';render();}
  else if(k==='pause'){paused=!paused;render();}
  else if(k==='skill'){const id=$('#skill-target')?.value;perform({type:'skill',...(id!==undefined&&id!==''?{id:+id}:{})});}
  else if(k==='exchange')perform({type:'exchange',id:+$('#exchange-target').value,give:$('#exchange-give').value,take:$('#exchange-take').value});
  else if(k==='export')exportFile(s);
  else if(k==='export-saved')exportFile(saved);
  else if(k==='import')$('#import-file').click();
  else if(k==='confirm-start')pendingStart?.();
  else if(k==='results'){resultClosed=false;results();}
 }catch(err){notify(err.message);}
});
document.addEventListener('input',e=>{if(e.target.dataset.name!==undefined)config.players[+e.target.dataset.name].name=e.target.value;});
document.addEventListener('change',e=>{
 const el=e.target;
 if(el.id==='count'){const n=+el.value;while(config.players.length<n){const p=player(config.players.length,config.solo);p.hero=order.find(k=>!config.players.some(x=>x.hero===k));config.players.push(p);}config.players=config.players.slice(0,n);setup();}
 if(el.id==='pace')config.pace=el.value;
 if(el.dataset.control!==undefined)config.players[+el.dataset.control].ai=el.value==='ai';
 if(el.dataset.hero!==undefined){const i=+el.dataset.hero,other=config.players.findIndex((p,j)=>j!==i&&p.hero===el.value),old=config.players[i].hero;if(other>=0){config.players[other].hero=old;delete config.players[other].stats;}config.players[i].hero=el.value;delete config.players[i].stats;setup();}
 if(el.dataset.stat){const [i,k]=el.dataset.stat.split(':'),p=config.players[i];if(!p.stats)p.stats=Object.fromEntries(stats.map((k,j)=>[k,HEROES[p.hero].stats[j]]));p.stats[k]=+el.value;}
 if(el.id.startsWith('exchange-'))exchangePreview();
});
document.addEventListener('submit',e=>{if(e.target.id==='setup-form'){e.preventDefault();try{createGame(config,1);start();}catch(err){notify(err.message);}}});
$('#dialog').addEventListener('cancel',e=>{e.preventDefault();if($('#dialog').dataset.closable==='true'){modal=null;resultClosed=true;$('#dialog').close();render();}});
$('#import-file').addEventListener('change',async e=>{
 const file=e.target.files[0];if(!file)return;
 try{if(file.size>2000000)throw Error('Fichier trop volumineux.');const value=validateSave(JSON.parse(await file.text()));const apply=()=>{s=value;view='game';modal=null;handoff=false;resultClosed=false;save();render();requestAnimationFrame(center);};
 if(saved&&!saved.finished){modal='replace-import';pendingStart=apply;open(dh('Charger cette sauvegarde')+'<p class="dialog-intro">Partie de '+value.players.map(p=>esc(p.name)).join(', ')+' · manche '+value.round+'. Elle remplacera votre sauvegarde automatique actuelle.</p><div class="dialog-footer">'+ui('Exporter la partie actuelle','export-saved')+ui('Charger la sauvegarde','confirm-start',true)+'</div>');}else apply();
 }catch(err){notify('Import impossible : '+err.message);}finally{e.target.value='';}
});
render();
